services:

  postgres:
    image: postgres:15
    container_name: cxp-postgres
    environment:
      POSTGRES_DB: cxp
      POSTGRES_USER: cxp_user
      POSTGRES_PASSWORD: cxp_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: cxp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cxp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    container_name: cxp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ai:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    container_name: cxp-ai
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    restart: unless-stopped

  ward-locator:
    build:
      context: ../ward-locator
      dockerfile: Dockerfile
    container_name: cxp-ward-locator
    ports:
      - "8081:8080"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cxp-backend
    depends_on:
      - postgres
      - ai
      - ward-locator
    ports:
      - "8080:8081"
    environment:
      SPRING_PROFILES_ACTIVE: admin,local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cxp
      SPRING_DATASOURCE_USERNAME: cxp_user
      SPRING_DATASOURCE_PASSWORD: cxp_pass

      AI_SERVICE_URL: http://ai:8000
      WARD_LOCATOR_BASE_URL: http://ward-locator:8080

      SALESFORCE_CLIENT_ID: 3MVG97L7PWbPq6Uz8ZKeySjFUHPWxO5WeYlllYhVqx5pDRNJjToMAFNuXBlWxQu9.HS9Bf95SmJa8ogP6VB19
      SALESFORCE_USERNAME: mayank@cirmorg.com
      SALESFORCE_LOGIN_URL: https://login.salesforce.com
      SALESFORCE_PRIVATE_KEY_PATH: classpath:keys/salesforce.key
    restart: unless-stopped

volumes:
  pgdata:
  ollama_data: