spring.profiles.active=admin


spring.datasource.url=jdbc:postgresql://localhost:5432/cxp
spring.datasource.username=cxp_user
spring.datasource.password=cxp_pass

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

salesforce.client-id=3MVG97L7PWbPq6Uz8ZKeySjFUHPWxO5WeYlllYhVqx5pDRNJjToMAFNuXBlWxQu9.HS9Bf95SmJa8ogP6VB19
salesforce.username=mayank@cirmorg.com
salesforce.login-url=https://login.salesforce.com
salesforce.private-key-path=classpath:keys/salesforce.key

security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
security.jwt.access-token-expiration-minutes=30
security.jwt.refresh-token-expiration-days=30
