package com.cxp.platform.governance.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/**
 * Reference/master data entity. IDs are assigned by Flyway seed migrations — never generated by JPA.
 * Does not use BaseEntity (consistent with Ward, GoverningBody, State, District).
 *
 * Hierarchy position: state → district → city → governing_body → zone → ward
 * Cities belong to exactly one district. A city may be administered by multiple governing bodies
 * (e.g. a cantonment board and a municipal corporation can coexist in the same city).
 *
 * Only active cities (is_active = true) are surfaced by the discovery API.
 */
@Entity
@Table(
        name = "city",
        indexes = {
                @Index(name = "idx_city_district", columnList = "district_id"),
                @Index(name = "idx_city_state",    columnList = "state_id")
        }
)
@Getter
@Setter
public class City {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Column(nullable = false, length = 255)
    private String name;

    @Column(length = 50)
    private String code;

    @Column(name = "district_id", nullable = false)
    private UUID districtId;

    @Column(name = "state_id", nullable = false)
    private UUID stateId;

    @Column(name = "is_active", nullable = false)
    private boolean active;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
