package com.cxp.platform.governance.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * Reference/master data entity for administrative districts.
 * IDs are assigned by Flyway seed migrations — never generated by JPA.
 */
@Entity
@Table(name = "district")
@Getter
@Setter
public class District {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Column(nullable = false, length = 255)
    private String name;

    @Column(name = "state_id", nullable = false)
    private UUID stateId;
}
