package com.cxp.platform.governance.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * Reference/master data entity. IDs are assigned by Flyway seed migrations — never generated by JPA.
 * Does not use BaseEntity (consistent with GoverningBody, City, State, District).
 *
 * Hierarchy position: state → district → city → governing_body → zone → ward
 * Ward is the atomic civic unit: the smallest addressable geographic boundary.
 * It drives announcement targeting, service request routing, and operator tenancy.
 * A ward belongs to exactly one governing body via the governing_body_id FK (NOT NULL).
 */
@Entity
@Table(name = "ward")
@Getter
@Setter
public class Ward {

    @Id
    @Column(nullable = false)
    private UUID id;

    @Column(name = "name")
    private String name;

    @Column(name = "zone_id")
    private UUID zoneId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "governing_body_id", nullable = false)
    private GoverningBody governingBody;
}
