-- ============================================================
-- Conversational AI Platform - V5
-- Stores AI chat sessions and message history for citizens
-- and municipal employees. Designed for multi-tenant SaaS,
-- audit retention and AI usage analytics.
-- ============================================================


-- ============================================================
-- TABLE: ai_conversation
-- Represents a single AI chat session (citizen or employee).
-- One user can have multiple conversations.
-- ============================================================

CREATE TABLE ai_conversation (
    id UUID PRIMARY KEY,
    conversation_type VARCHAR(30) NOT NULL, -- CITIZEN / EMPLOYEE
    user_id UUID NOT NULL,
    municipality_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL, -- ACTIVE / CLOSED

    started_at TIMESTAMP NOT NULL,
    last_message_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_conversation IS
'Stores AI chat sessions for citizens and employees. Multi-tenant and audit compliant.';

COMMENT ON COLUMN ai_conversation.conversation_type IS
'Type of user initiating the chat: CITIZEN or EMPLOYEE';

COMMENT ON COLUMN ai_conversation.user_id IS
'Reference to platform user initiating the conversation';

COMMENT ON COLUMN ai_conversation.municipality_id IS
'Tenant isolation identifier. Ensures conversations are scoped per municipality';

COMMENT ON COLUMN ai_conversation.status IS
'Conversation lifecycle state: ACTIVE or CLOSED';

COMMENT ON COLUMN ai_conversation.started_at IS
'Timestamp when the conversation session started';

COMMENT ON COLUMN ai_conversation.last_message_at IS
'Timestamp of the most recent message for analytics and cleanup jobs';


-- Indexes for fast tenant filtering and session lookups
CREATE INDEX idx_ai_conv_user
    ON ai_conversation(user_id);

CREATE INDEX idx_ai_conv_municipality
    ON ai_conversation(municipality_id);

CREATE INDEX idx_ai_conv_last_message
    ON ai_conversation(last_message_at);



-- ============================================================
-- TABLE: ai_message
-- Stores every user prompt and AI response.
-- Used for audit trail, context retrieval and cost tracking.
-- ============================================================

CREATE TABLE ai_message (
    id UUID PRIMARY KEY,
    conversation_id UUID NOT NULL,
    role VARCHAR(20) NOT NULL, -- USER / ASSISTANT / SYSTEM

    content TEXT NOT NULL,

    model VARCHAR(50), -- AI model used (nullable for USER messages)

    prompt_tokens INT,
    completion_tokens INT,
    total_tokens INT,

    response_time_ms INT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ai_message_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES ai_conversation(id)
);

COMMENT ON TABLE ai_message IS
'Stores full AI chat history including user prompts and AI responses.';

COMMENT ON COLUMN ai_message.role IS
'Origin of the message: USER, ASSISTANT, or SYSTEM';

COMMENT ON COLUMN ai_message.model IS
'AI model used to generate the response (e.g., llama3). Used for analytics and billing';

COMMENT ON COLUMN ai_message.prompt_tokens IS
'Number of tokens in the input prompt sent to the model';

COMMENT ON COLUMN ai_message.completion_tokens IS
'Number of tokens generated by the model';

COMMENT ON COLUMN ai_message.total_tokens IS
'Total tokens consumed for the request (prompt + completion)';

COMMENT ON COLUMN ai_message.response_time_ms IS
'Time taken by AI service to generate the response in milliseconds';


-- Critical index for retrieving conversation context quickly
CREATE INDEX idx_ai_msg_conversation_created
    ON ai_message(conversation_id, created_at DESC);
